[package]
name = "agentnexus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
rhai = "1.16.2"
rhai-rand = "0.1.5"
serde_json = "1.0.107"
