[package]
name = "agentnexus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.3"
futures = "0.3.28"
once_cell = "1.18.0"
rhai = { version = "1.16.2", features = [ "serde" ] }
rhai-rand = "0.1.5"
serde = "1.0.189"
serde_json = "1.0.107"
tiktoken-rs = "0.5.4"
tokio = { version = "1.33.0", features = [ "full" ] }

