[package]
name = "agenthost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-openai = "0.14.3"
bytes = "1.5.0"
chrono = "0.4.31"
flume = "0.11.0"
futures = "0.3.28"
futures-util = "0.3.28"
jsonwebtoken = "9.1.0"
once_cell = "1.18.0"
pretty_env_logger = "0.5.0"
regex = "1.10.2"
rhai = { version = "1.16.2", features = [ "serde" ] }
rhai-fs = "0.1.2"
rhai-rand = "0.1.5"
serde = "1.0.189"
serde_json = "1.0.107"
smartstring = "1.0.1"
termimad = "0.25.5"
termion = "2.0.1"
tiktoken-rs = "0.5.4"
tokio = { version = "1.33.0", features = [ "full" ] }
tokio-stream = "0.1.14"
tower-http = "0.3"

